export const data = [
  {
    id: "stage1",
    name: "First Stage",
    processes: [
      {
        id: "11process",
        name: "First Process",
        tasks: [
          {
            id: "111",
            name: "First task",
          },
          {
            id: "1123",
            name: "Second Task",
          },
        ],
      },
      {
        id: "12process",
        name: "Second Process",
        tasks: [
          {
            id: "111",
            name: "First task",
          },
          {
            id: "1123",
            title: "Second Task",
          },
        ],
      },
    ],
  },
  {
    id: "stage2",
    name: "Second Stage",
    processes: [
      {
        id: "11process",
        name: "First Process",
        tasks: [
          {
            id: "111",
            name: "First task",
          },
          {
            id: "1123",
            name: "Second Task",
          },
        ],
      },
      {
        id: "12process",
        name: "Second Process",
        tasks: [
          {
            id: "111",
            name: "First task",
          },
          {
            id: "1123",
            name: "Second Task",
          },
        ],
      },
    ],
  },
];

export const commercialOnbData = [
  {
    id: "f8d203fb-371d-463e-9a4e-9793ce9dbb",
    name: "New Application",
    status: "Not Started",
    order: 0,
    started: null,
    completed: null,
    processes: [
      {
        id: "f8d203fb-371d-463e-9a4e-9793ce9edbb",
        name: "Capture Basic Details",
        status: "Not Started",
        order: 0,
        tasks: [
          {
            kycTarget: "client",
            kycCategory: null,
            kycRequirementType: "data",
            businessCategory: null,
            businessSubCategory: null,
            id: "f8d203fb-d-463e-9a4ee91edbb",
            name: "Capture Basic Details",
            status: "Not Started",
            order: 0,
            taskType: "KycTask",
            discriminator: "KycTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
    ],
  },
  {
    id: "f8d203fb-3-463e-9a4e-9793ce91edbb",
    name: "Customer Profile",
    status: "Not Started",
    order: 1,
    started: null,
    completed: null,
    processes: [
      {
        id: "f8d203fb71d-463e-9a4e-9793ce91edbb",
        name: "Customer Profile",
        status: "Not Started",
        order: 0,
        tasks: [
          {
            kycTarget: "client",
            kycCategory: null,
            kycRequirementType: "data",
            businessCategory: null,
            businessSubCategory: null,
            id: "f8d203fb9a4e-9793ce91edbb",
            name: "Capture Customer Profile",
            status: "Not Started",
            order: 0,
            taskType: "KycTask",
            discriminator: "KycTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
          {
            id: "f8d203f3ce91edbb",
            name: "Verify with External Sources",
            status: "Not Started",
            order: 1,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
          {
            id: "f8d23e-9a4e-9793ce91edbb",
            name: "Deduplicate",
            status: "Not Started",
            order: 2,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
      {
        id: "f8d203fb-371d-4633ce91edbb",
        name: "Document Requirements",
        status: "Not Started",
        order: 1,
        tasks: [
          {
            kycTarget: "client",
            kycCategory: null,
            kycRequirementType: "document",
            businessCategory: null,
            businessSubCategory: null,
            id: "f8d203fb-9a4e-9793ce91edbb",
            name: "Satisfy Document Requirements",
            status: "Not Started",
            order: 0,
            taskType: "KycTask",
            discriminator: "KycTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
          {
            id: "f8d203fb3e-9a4e-9793ce91edbb",
            name: "Enrich Customer Profile",
            status: "Not Started",
            order: 1,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
      {
        id: "f8d203fb-34e-9793ce91edbb",
        name: "Ownership and Control",
        status: "Not Started",
        order: 1,
        tasks: [
          {
            kycTarget: "client",
            kycCategory: null,
            kycRequirementType: "ownership and control",
            businessCategory: null,
            businessSubCategory: null,
            id: "f83e-9a4e-9793ce91edbb",
            name: "Ownership and Control Requirements",
            status: "Not Started",
            order: 0,
            taskType: "KycTask",
            discriminator: "KycTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
    ],
  },
  {
    id: "f8d203fb-371d-493ce91edbb",
    name: "Customer Checks",
    status: "Not Started",
    order: 2,
    started: null,
    completed: null,
    processes: [
      {
        id: "f8d203fb3ce91edbb",
        name: "AML Screening",
        status: "Not Started",
        order: 0,
        tasks: [
          {
            id: "f8d203fb-b9793ce91edbb",
            name: "Screen with Industry Providers",
            status: "Not Started",
            order: 0,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
          {
            id: "f8d203fb-,mn,ce91edbb",
            name: "Resolve Screening Hits",
            status: "Not Started",
            order: 1,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
      {
        id: "fnm,3e-9a4e-9793ce91edbb",
        name: "Risk Assessment",
        status: "Not Started",
        order: 1,
        tasks: [
          {
            id: "f8d203ffgh9793ce91edbb",
            name: "Calculate Risk Rating",
            status: "Not Started",
            order: 0,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
    ],
  },
  {
    id: "f8d203gfhfgh93ce91edbb",
    name: "Review",
    status: "Not Started",
    order: 3,
    started: null,
    completed: null,
    processes: [
      {
        id: "f8d203fb-371d-4fghe91edbb",
        name: "Onboarding Review",
        status: "Not Started",
        order: 0,
        tasks: [
          {
            id: "f8d203fbdh91edbb",
            name: "Review Customer Profile",
            status: "Not Started",
            order: 0,
            taskType: "ManualTask",
            discriminator: "ManualTask",
            assignedTo: null,
            started: "0001-01-01T00:00:00+00:00",
            completed: "0001-01-01T00:00:00+00:00",
            cancelled: "0001-01-01T00:00:00+00:00",
            completedBy: null,
          },
        ],
        started: null,
        completed: null,
      },
    ],
  },
];
